<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS03_Catagory</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f3ee322c-0c2f-40d8-b375-6f0d2c5b4bac</testSuiteGuid>
   <testCaseLink>
      <guid>f30ea571-e03b-4869-a839-b02bb9ef410b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Catagory Task/TC01_Verify Add Catagory Successuflly</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>514b06e6-e998-47fa-834e-ea877d02329b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16166c7a-867c-49cf-a70e-69c1e4b4f2e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Catagory Task/TC02_Verify Delete Catagory Successuflly</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4b334e7-8b02-4862-b497-6d2927d8d77c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>030cab63-0f56-45b5-a499-30b26055a9a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb048a79-af77-4d58-87fd-34684bf471d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Catagory Task/TC03_Verify Update Catagory Successuflly</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a114b881-c6b9-4a3c-a983-92f9503af876</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08f7f86d-9b65-47d4-b445-864382ae8c7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f55c71b0-2d51-4e4a-8c1a-ff43cb9abf70</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Catagory Task/TC04_Verify Add Catagory Cencel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>113d9160-9369-46cb-8dce-b2b049ec3fec</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
