<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS03_Catagory</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f3ee322c-0c2f-40d8-b375-6f0d2c5b4bac</testSuiteGuid>
   <testCaseLink>
      <guid>37073aad-b835-4725-a376-7250b8b1de94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Function/TC_Catagory/TC01_Verify Add Catagory Successuflly</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6fbd9710-8ad8-4722-932e-3275b5d1c52e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/KatalonData/Catagory</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6fbd9710-8ad8-4722-932e-3275b5d1c52e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>AddCatagorys</value>
         <variableId>514b06e6-e998-47fa-834e-ea877d02329b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bea5b31-9993-453d-9798-712604753c05</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Function/TC_Catagory/TC02_Verify Delete Catagory Successuflly</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d1539362-4f39-4115-ab54-63055e35eb54</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/KatalonData/Catagory</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d1539362-4f39-4115-ab54-63055e35eb54</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CatagoryNameDelete</value>
         <variableId>030cab63-0f56-45b5-a499-30b26055a9a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8c9731e-822c-4860-a4fd-63c501c9cd46</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Function/TC_Catagory/TC03_Verify Update Catagory Successuflly</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>32419111-f84c-465c-b96f-1739583b9d87</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/KatalonData/Catagory</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>32419111-f84c-465c-b96f-1739583b9d87</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CatagoryName</value>
         <variableId>360dbd32-e0d0-4d9a-bd9d-e494385c6600</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>32419111-f84c-465c-b96f-1739583b9d87</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CatagoryNameEdit</value>
         <variableId>34f34ec1-6614-472b-b220-5bf789942ecf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>981c66a9-83ba-4d62-9ae3-71a4b1d1ba78</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Function/TC_Catagory/TC04_Verify Add, Edit, and Delete Catagory Successuflly</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f3fb6f67-e6e6-488f-8b80-13ab052ca95d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/KatalonData/Catagory</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f3fb6f67-e6e6-488f-8b80-13ab052ca95d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>AddCatagorys</value>
         <variableId>e8fce8e7-e565-4804-8adc-2a7addf2d60c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f3fb6f67-e6e6-488f-8b80-13ab052ca95d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>EditCatagorys</value>
         <variableId>a3e1a73c-b347-408e-a873-091c088fee40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4b53610-ee77-425e-a6be-c7ce31148df2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Function/TC_Catagory/TC05_Verify Add Catagory Cencel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5828d201-40be-4145-9f6e-cea1f4df11c1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/KatalonData/Catagory</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>5828d201-40be-4145-9f6e-cea1f4df11c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>AddCatagorys</value>
         <variableId>113d9160-9369-46cb-8dce-b2b049ec3fec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3ac5df4-3956-4450-85a2-7865f4659755</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Function/TC_Catagory/TC06_Verify Delete Catagory Cencel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3f57783e-f392-47e2-b4f4-8e57a5dc2d6b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/KatalonData/Catagory</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3f57783e-f392-47e2-b4f4-8e57a5dc2d6b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CatagoryNameDelete</value>
         <variableId>a1f1f29f-c947-482e-af72-9f93aa884806</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3a822bcd-75b2-4eaa-a129-b826242b3f3f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Function/TC_Catagory/TC07_Verify Update Catagory Failed</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4a1f55d8-cb1f-4012-b195-179537a900b0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/KatalonData/Catagory</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4a1f55d8-cb1f-4012-b195-179537a900b0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>SameCatagoryName</value>
         <variableId>61f81406-ab60-4e13-ab8c-6f8775468fe8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4a1f55d8-cb1f-4012-b195-179537a900b0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CatagoryNameEdit</value>
         <variableId>4726f80d-24a0-41b0-8c57-e040d307f6bf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
